apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-analyzer-config
data:
  LOG_LEVEL: {{ .Values.ocrAnalyzer.logLevel }}
  GPU_ENABLED: {{ .Values.ocrAnalyzer.gpuEnabled | quote }}
  OCR_LANGUAGES: {{ .Values.ocrAnalyzer.ocrLanguages | quote }}
  