apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  JWT_ALGORITHM: {{ .Values.fileUploader.jwtAlgorithm }}
  LOG_LEVEL: {{ .Values.fileUploader.logLevel }}
  DB_NAME: {{ .Values.mongodb.dbName }}