apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader
spec:
  selector:
    matchLabels:
      app: file-uploader
  template:
    metadata:
      labels:
        app: file-uploader
    spec:
      containers:
        - name: file-uploader
          image: gerencsermate/file-uploader:{{ .Values.env.FILE_UPLOADER_IMAGE_VERSION }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGODB_URL
          volumeMounts:
            - name: uploaded-files-volume
              mountPath: /app/UPLOADED_FILES
      volumes:
        - name: uploaded-files-volume        # Ez egy tetszőleges név a Pod-on belül
          persistentVolumeClaim:
            claimName: file-uploader-pvc
