apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.fileUploader.jwtSecret | b64enc }}
  MONGODB_URL: {{ printf "mongodb://%s:%s@mongodb-service:27017" .Values.mongodb.username .Values.mongodb.password | b64enc }}