apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.fileUploader.jwtSecret | b64enc }}
  MONGODB_URL: {{ printf "mongodb://%s:%s@mongodb-service:27017/%s" .Values.mongodb.username .Values.mongodb.password  .Values.mongodb.dbName | b64enc }}