apiVersion: v1
kind: Service
metadata:
  name: notification-sender
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: notification-sender
