env:
  FILE_UPLOADER_IMAGE_VERSION: "5143ca8f0beb3042e9f37eafd97d926968c0db73"
  NOTIFICATION_SENDER_IMAGE_VERSION: "5143ca8f0beb3042e9f37eafd97d926968c0db73"

mongodb:
  username: admin
  password: admin
  dbName: ocr-db

fileUploader:
  logLevel: INFO
  jwtAlgorithm: HS256
  jwtSecret: TestJwtSecret
