env:
  FILE_UPLOADER_IMAGE_VERSION: "b13b09be21ab112c0fbb03aef9f2ab47f2fb39e5"
  NOTIFICATION_SENDER_IMAGE_VERSION: "b13b09be21ab112c0fbb03aef9f2ab47f2fb39e5"

mongodb:
  username: admin
  password: admin
  dbName: ocr-db

fileUploader:
  logLevel: INFO
  jwtAlgorithm: HS256
  jwtSecret: TestJwtSecret
