env:
  FILE_UPLOADER_IMAGE_VERSION: "0b44a0e43598a64f7b62193ed33dfe5e4d85afdd"
  NOTIFICATION_SENDER_IMAGE_VERSION: "0b44a0e43598a64f7b62193ed33dfe5e4d85afdd"
  OCR_ANALYZER_IMAGE_VERSION: "0b44a0e43598a64f7b62193ed33dfe5e4d85afdd"

mongodb:
  username: admin
  password: admin
  dbName: ocr-db

fileUploader:
  logLevel: INFO
  jwtAlgorithm: HS256
  jwtSecret: TestJwtSecret
  ocrUrl: http://ocr-analyzer-service:9000

ocrAnalyzer:
  logLevel: INFO
  gpuEnabled: false
  ocrLanguages: hu,en
